In [2]:
from matplotlib import dates as mdate
from matplotlib import pyplot as plt
import matplotlib.animation as animation
import pandas as pd
from time import sleep
from IPython.display import clear_output
import numpy as np

In [5]:

aOptimal = pd.read_csv("../Trainable data/Anthony/Anthony_Optimal_Training_Data.csv")
aInoptimal = pd.read_csv("../Trainable data/Anthony/Anthony_Inoptimal_Training_Data.csv")

# cdate = m["Elapsed Time (s)"]

# print(m)

# PhoneAccelZ = m["Phone-Accel-Z"]
# PhoneAccelY = m["Phone-Accel-Y"]
# PhoneAccelX = m["Phone-Accel-X"]

# WatchAccelZ = m["Watch-Accel-Z"]
# WatchAccelY = m["Watch-Accel-Y"]
# WatchAccelX = m["Watch-Accel-X"]

# PhoneGyroZ = m["Phone-Gyro-Z"]
# PhoneGyroY = m["Phone-Gyro-Y"]
# PhoneGyroX = m["Phone-Gyro-X"]

# WatchGyroZ = m["Watch-Gyro-Z"]
# WatchGyroY = m["Watch-Gyro-Y"]
# WatchGyroX = m["Watch-Gyro-X"]

# PhoneMagZ = m["Phone-Mag-Z"]
# PhoneMagY = m["Phone-Mag-Y"]
# PhoneMagX = m["Phone-Mag-X"]

# WatchMagZ = m["Watch-Mag-Z"]
# WatchMagY = m["Watch-Mag-Y"]
# WatchMagX = m["Watch-Mag-X"]

In [6]:
aOptimal

Stroke Number                                      Phone-Accel-Z  \
0               0  [-0.5926971436, -0.5915374756, -0.5438079834, ...   
1               1  [0.07754516602, 0.06880187988, 0.08319091797, ...   
2               2  [-0.03887939453, -0.02210998535, -0.0249328613...   
3               3  [-0.07922363281, -0.07525634766, -0.0437316894...   
4               4  [0.04374694824, 0.05906677246, 0.06971740723, ...   
5               5  [-0.05625915527, -0.03067016602, -0.0318603515...   
6               6  [-0.02326965332, -0.01356506348, -0.0059051513...   
7               7  [0.05555725098, 0.05223083496, 0.05535888672, ...   
8               8  [-0.04559326172, -0.04362487793, -0.0348510742...   
9               9  [-0.2394256592, -0.1639709473, 0.02305603027, ...   
10             10  [0.1306152344, 0.1335144043, 0.1377868652, 0.1...   
11             11  [-0.03982543945, -0.02464294434, 0.01469421387...   
12             12  [0.1080322266, 0.1009521484, 0.09527587891, 0....   
13             13  [0.1267700195, 0.1360473633, 0.1382293701, 0.1...   
14             14  [0.05685424805, 0.04998779297, 0.02122497559, ...   
15             15  [0.16746521, 0.1658630371, 0.1552276611, 0.146...   
16             16  [0.03594970703, 0.03549194336, 0.02645874023, ...   
17             17  [0.02375793457, 0.03190612793, 0.04438781738, ...   
18             18  [0.1217803955, 0.1270599365, 0.1353759766, 0.1...   
19             19  [0.07672119141, 0.07443237305, 0.05889892578, ...   
20             20  [0.04194641113, 0.0478515625, 0.05703735352, 0...   
21             21  [0.07498168945, 0.05683898926, 0.04267883301, ...   
22             22  [0.09541320801, 0.06234741211, 0.04217529297, ...   
23             23  [0.07023620605, 0.06596374512, 0.05313110352, ...   
24             24  [0.1112365723, 0.1060028076, 0.1085205078, 0.1...   
25             25  [0.06762695313, 0.06477355957, 0.05757141113, ...   
26             26  [0.07427978516, 0.06817626953, 0.07023620605, ...   
27             27  [0.04067993164, 0.03219604492, 0.03176879883, ...   
28             28  [0.1107025146, 0.08683776855, 0.08163452148, 0...   
29             29  [0.08444213867, 0.06652832031, 0.05130004883, ...   
30             30  [0.03979492188, 0.03709411621, 0.04840087891, ...   
31             31  [0.1035919189, 0.08618164063, 0.06677246094, 0...   
32             32  [0.08752441406, 0.08369445801, 0.08262634277, ...   

                                        Phone-Accel-Y  \
0   [0.6248931885, 0.6346282959, 0.6983947754, 0.7...   
1   [0.1813659668, 0.168762207, 0.1533203125, 0.12...   
2   [0.5364685059, 0.4570617676, 0.4031219482, 0.3...   
3   [0.5011138916, 0.5008544922, 0.5012817383, 0.4...   
4   [0.4012908936, 0.3593902588, 0.3299102783, 0.3...   
5   [0.3690643311, 0.3277282715, 0.2731933594, 0.2...   
6   [0.2865447998, 0.22605896, 0.1948699951, 0.197...   
7   [0.3318634033, 0.3109893799, 0.3007202148, 0.3...   
8   [0.4451293945, 0.3870697021, 0.3539581299, 0.3...   
9   [0.4408569336, 0.3381652832, 0.3094177246, 0.3...   
10  [0.3588104248, 0.3544921875, 0.345413208, 0.33...   
11  [0.5706176758, 0.5110626221, 0.4656066895, 0.4...   
12  [0.39453125, 0.3382263184, 0.309173584, 0.3017...   
13  [0.4156646729, 0.4226531982, 0.4246673584, 0.4...   
14  [0.4625396729, 0.429977417, 0.4134216309, 0.40...   
15  [0.4467315674, 0.4293365479, 0.4188690186, 0.4...   
16  [0.5519561768, 0.5371856689, 0.5122680664, 0.4...   
17  [0.4387664795, 0.4287261963, 0.414642334, 0.39...   
18  [0.514541626, 0.4981842041, 0.4964141846, 0.49...   
19  [0.2838745117, 0.2605438232, 0.2341918945, 0.2...   
20  [0.4071807861, 0.3685760498, 0.3371734619, 0.3...   
21  [0.3446350098, 0.3208007813, 0.3039703369, 0.2...   
22  [0.3212738037, 0.2822570801, 0.2500762939, 0.2...   
23  [0.3632659912, 0.340423584, 0.3194580078, 0.31...   
24  [0.4618682861, 0.4254455566, 0.3973693848, 0.3...   
25  [0.4050292969, 0.3603210449, 0.3274230957, 0.3...   
26  [0.282638549

In [7]:
aInoptimal

Stroke Number                                      Phone-Accel-Z  \
0               1  [0.02252197266, 0.0223236084, 0.01182556152, -...   
1               2  [0.2255554199, 0.2437591553, 0.2324066162, 0.2...   
2               3  [0.2607879639, 0.2749023438, 0.2628173828, 0.2...   
3               4  [0.06538391113, 0.05882263184, 0.06071472168, ...   
4               5  [0.2081451416, 0.2085571289, 0.1977233887, 0.1...   
5               6  [0.120880127, 0.1168365479, 0.1277770996, 0.14...   
6               7  [0.2472839355, 0.2868041992, 0.3089294434, 0.3...   
7               8  [0.2234954834, 0.2342681885, 0.2314910889, 0.2...   
8               9  [0.1620788574, 0.1602783203, 0.1701507568, 0.1...   
9              10  [0.1593780518, 0.1446533203, 0.1313934326, 0.1...   
10             11  [0.1704559326, 0.1838684082, 0.1934509277, 0.1...   
11             12  [0.05880737305, 0.06723022461, 0.06831359863, ...   
12             13  [0.06178283691, 0.07974243164, 0.08232116699, ...   
13             14  [0.1244049072, 0.1257781982, 0.1312408447, 0.1...   
14             15  [0.09994506836, 0.08807373047, 0.08094787598, ...   
15             16  [0.1340332031, 0.1444244385, 0.1521148682, 0.1...   
16             17  [0.2841033936, 0.2811889648, 0.2763214111, 0.2...   
17             18  [0.2700653076, 0.2699584961, 0.2660980225, 0.2...   
18             19  [-0.1029663086, -0.1184844971, -0.1431732178, ...   
19             20  [0.209487915, 0.2163238525, 0.2249755859, 0.23...   

                                        Phone-Accel-Y  \
0   [0.4726867676, 0.4757080078, 0.4613647461, 0.4...   
1   [0.4441375732, 0.4008789063, 0.3825073242, 0.3...   
2   [0.3986816406, 0.3873138428, 0.3898620605, 0.4...   
3   [0.5975799561, 0.5753479004, 0.5684356689, 0.5...   
4   [0.536605835, 0.51121521, 0.4959411621, 0.4884...   
5   [0.5467834473, 0.5296936035, 0.5214691162, 0.5...   
6   [0.4577636719, 0.4615783691, 0.4690246582, 0.4...   
7   [0.4727325439, 0.4585723877, 0.4617004395, 0.4...   
8   [0.512298584, 0.5088043213, 0.5048065186, 0.50...   
9   [0.8192901611, 0.7966308594, 0.7819061279, 0.7...   
10  [0.7669830322, 0.7767028809, 0.7657623291, 0.7...   
11  [0.7363128662, 0.7263946533, 0.7330322266, 0.7...   
12  [0.8278045654, 0.8032073975, 0.7757873535, 0.7...   
13  [0.8118286133, 0.7918243408, 0.7626647949, 0.7...   
14  [0.6478881836, 0.5876617432, 0.5291442871, 0.4...   
15  [0.703125, 0.6952514648, 0.6788635254, 0.67132...   
16  [0.6890106201, 0.6761169434, 0.6697998047, 0.6...   
17  [0.796005249, 0.7783050537, 0.7419433594, 0.71...   
18  [0.6134185791, 0.5330352783, 0.4633026123, 0.4...   
19  [0.8119354248, 0.7904968262, 0.77394104, 0.764...   

                                        Phone-Accel-X  \
0   [-0.800201416, -0.8127593994, -0.8165740967, -...   
1   [-0.7686004639, -0.7867584229, -0.8179779053, ...   
2   [-0.8255310059, -0.8410186768, -0.849609375, -...   
3   [-0.7298583984, -0.7517547607, -0.7610931396, ...   
4   [-0.7803497314, -0.7706298828, -0.752746582, -...   
5   [-0.7122497559, -0.7206268311, -0.7317657471, ...   
6   [-0.830871582, -0.8439331055, -0.8478546143, -...   
7   [-0.7662963867, -0.7651367188, -0.7675018311, ...   
8   [-0.8002929688, -0.812286377, -0.8013916016, -...   
9   [-0.5373840332, -0.5224304199, -0.5067749023, ...   
10  [-0.5520324707, -0.5350494385, -0.5328979492, ...   
11  [-0.6577758789, -0.6611633301, -0.6401824951, ...   
12  [-0.5853424072, -0.5844573975, -0.5908508301, ...   
13  [-0.5860443115, -0.5893554688, -0.5917053223, ...   
14  [-0.5213317871, -0.5388641357, -0.5706329346, ...   
15  [-0.6776733398, -0.683303833, -0.6791534424, -...   
16  [-0.6949920654, -0.6806335449, -0.6586151123, ...   
17  [-0.5181121826, -0.5224456787, -0.5354156494, ...   
18  [-0.7963256836, -0.7773895264, -0.7286987305, ...   
19  [-0.734588623, -0.7503509521, -0.7486114502, -...   

                                        Watch-Accel-Z  \
0   [-0.9678497314, -0.9629821777, -0.

In [14]:
row0 = aOptimal.iloc[0].values.tolist()[1:]
row0

['[-0.5926971436, -0.5915374756, -0.5438079834, -0.599319458, -0.6508636475, -0.6382141113, -0.722076416, -0.7423400879, -0.454284668, -0.5820770264, -0.4512481689, -0.4465637207, -0.4397888184, -0.4188537598, -0.4470977783, -0.4178466797, -0.3692474365, -0.3867645264, -0.4296264648, -0.4797363281, -0.4984741211, -0.4956665039, -0.4321136475, -0.4044036865, -0.3761444092, -0.3491363525, -0.3654022217, -0.4157562256, -0.4202270508, -0.3878173828, -0.3428344727, -0.2797088623, -0.3149719238, -0.371383667, -0.3583831787, -0.3320617676, -0.3522491455, -0.388168335, -0.4199371338, -0.432144165, -0.4015350342, -0.4331817627, -0.4928741455, -0.4782714844, -0.4557189941, -0.4775238037, -0.4286346436, -0.3921203613, -0.3106994629, -0.272857666, -0.3385467529, -0.4188995361, -0.4333648682, -0.4354553223, -0.3915710449, -0.3218383789, -0.2838439941, -0.2830657959, -0.2706756592, -0.3034515381, -0.3372497559, -0.3895263672, -0.3761138916, -0.3607330322, -0.3152160645, -0.3110198975, -0.237701416, 

In [15]:
type(row0)

list

In [16]:
row0[0]

'[-0.5926971436, -0.5915374756, -0.5438079834, -0.599319458, -0.6508636475, -0.6382141113, -0.722076416, -0.7423400879, -0.454284668, -0.5820770264, -0.4512481689, -0.4465637207, -0.4397888184, -0.4188537598, -0.4470977783, -0.4178466797, -0.3692474365, -0.3867645264, -0.4296264648, -0.4797363281, -0.4984741211, -0.4956665039, -0.4321136475, -0.4044036865, -0.3761444092, -0.3491363525, -0.3654022217, -0.4157562256, -0.4202270508, -0.3878173828, -0.3428344727, -0.2797088623, -0.3149719238, -0.371383667, -0.3583831787, -0.3320617676, -0.3522491455, -0.388168335, -0.4199371338, -0.432144165, -0.4015350342, -0.4331817627, -0.4928741455, -0.4782714844, -0.4557189941, -0.4775238037, -0.4286346436, -0.3921203613, -0.3106994629, -0.272857666, -0.3385467529, -0.4188995361, -0.4333648682, -0.4354553223, -0.3915710449, -0.3218383789, -0.2838439941, -0.2830657959, -0.2706756592, -0.3034515381, -0.3372497559, -0.3895263672, -0.3761138916, -0.3607330322, -0.3152160645, -0.3110198975, -0.237701416, -

In [17]:
type(row0[0])

str

In [147]:
xarr = []
yarr = []

In [148]:
aOptimal.shape[0]

33

In [149]:
u = 1
while (u < aOptimal.shape[0]):
    
    row0 = aOptimal.iloc[u].values.tolist()[1:]
    
    rfin = []

    p = 0
    while (p < len(row0)):

        row0[p] = row0[p][1:-1]
        row0[p] = row0[p].split(",")

        k = 0
        while (k < len(row0[p]) and k < 155):
            # effectively flatten it
#             row0[p][k] = float(row0[p][k])
            rfin.append(float(row0[p][k]))
            k += 1
        
        # print the length of features in that stroke
        print(k)

        p += 1
    
    u += 1
    
    xarr.append(rfin)
    yarr.append(0)
    

155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155


In [150]:
u = 0
while (u < aInoptimal.shape[0]):
    
    row0 = aInoptimal.iloc[u].values.tolist()[1:]
    
    rfin = []

    p = 0
    while (p < len(row0)):

        row0[p] = row0[p][1:-1]
        row0[p] = row0[p].split(",")

        k = 0
        while (k < len(row0[p]) and k < 155):
            # effectively flatten it
#             row0[p][k] = float(row0[p][k])
            rfin.append(float(row0[p][k]))
            k += 1
        
        # print the length of features in that stroke
        print(k)

        p += 1
    
    u += 1
    
    xarr.append(rfin)
    yarr.append(1)

155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155
155


In [151]:
xarr

[[0.07754516602,
  0.06880187988,
  0.08319091797,
  0.1128845215,
  0.1298217773,
  0.1511230469,
  0.1649169922,
  0.1790466309,
  0.1768341064,
  0.1564331055,
  0.1277008057,
  0.1148071289,
  0.1172180176,
  0.1137237549,
  0.1025848389,
  0.102355957,
  0.08155822754,
  0.04475402832,
  0.04330444336,
  0.04942321777,
  0.05854797363,
  0.06921386719,
  0.04861450195,
  -0.002395629883,
  -0.04220581055,
  -0.04536437988,
  -0.02279663086,
  -0.01860046387,
  -0.05221557617,
  -0.08183288574,
  -0.07948303223,
  -0.04386901855,
  -0.01203918457,
  -0.04116821289,
  -0.1007080078,
  -0.1214904785,
  -0.1483459473,
  -0.1729278564,
  -0.1820220947,
  -0.1859893799,
  -0.2507171631,
  -0.3163452148,
  -0.2416992188,
  -0.1342010498,
  -0.1817932129,
  -0.213394165,
  -0.2054138184,
  -0.2276306152,
  -0.2623138428,
  -0.2573242188,
  -0.4158477783,
  -0.4336700439,
  -0.2797698975,
  -0.358505249,
  -0.2686309814,
  -0.3195037842,
  -0.346206665,
  -0.3460388184,
  -0.3201446533,
  

In [152]:
yarr

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [81]:
type(xarr)

list

In [82]:
type(xarr[0])

list

In [121]:
xarr = [[1, 1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1],[2, 1, 1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1],[2, 1, 1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1],[2, 1, 1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1],[2, 1, 1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1, -1,-1]]

In [116]:
type(xarr)

list

In [117]:
type(xarr[0])

list

In [153]:
xarr

[[0.07754516602,
  0.06880187988,
  0.08319091797,
  0.1128845215,
  0.1298217773,
  0.1511230469,
  0.1649169922,
  0.1790466309,
  0.1768341064,
  0.1564331055,
  0.1277008057,
  0.1148071289,
  0.1172180176,
  0.1137237549,
  0.1025848389,
  0.102355957,
  0.08155822754,
  0.04475402832,
  0.04330444336,
  0.04942321777,
  0.05854797363,
  0.06921386719,
  0.04861450195,
  -0.002395629883,
  -0.04220581055,
  -0.04536437988,
  -0.02279663086,
  -0.01860046387,
  -0.05221557617,
  -0.08183288574,
  -0.07948303223,
  -0.04386901855,
  -0.01203918457,
  -0.04116821289,
  -0.1007080078,
  -0.1214904785,
  -0.1483459473,
  -0.1729278564,
  -0.1820220947,
  -0.1859893799,
  -0.2507171631,
  -0.3163452148,
  -0.2416992188,
  -0.1342010498,
  -0.1817932129,
  -0.213394165,
  -0.2054138184,
  -0.2276306152,
  -0.2623138428,
  -0.2573242188,
  -0.4158477783,
  -0.4336700439,
  -0.2797698975,
  -0.358505249,
  -0.2686309814,
  -0.3195037842,
  -0.346206665,
  -0.3460388184,
  -0.3201446533,
  

In [154]:
X = np.array(xarr)

y = np.array(yarr)

In [155]:
X

array([[ 7.75451660e-02,  6.88018799e-02,  8.31909180e-02, ...,
         1.37641327e+02,  1.37967133e+02,  1.37851166e+02],
       [-3.88793945e-02, -2.21099853e-02, -2.49328613e-02, ...,
         1.38776810e+02,  1.38790558e+02,  1.38839233e+02],
       [-7.92236328e-02, -7.52563477e-02, -4.37316894e-02, ...,
         1.38367050e+02,  1.38225815e+02,  1.38413101e+02],
       ...,
       [ 2.70065308e-01,  2.69958496e-01,  2.66098022e-01, ...,
         1.59204590e+02,  1.59235763e+02,  1.59317444e+02],
       [-1.02966309e-01, -1.18484497e-01, -1.43173218e-01, ...,
         1.60044815e+02,  1.59853882e+02,  1.59837357e+02],
       [ 2.09487915e-01,  2.16323852e-01,  2.24975586e-01, ...,
         1.55824158e+02,  1.55920593e+02,  1.56143082e+02]])

In [156]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [74]:
# X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])

# y = np.array([1, 1, 2, 2])

In [75]:
X

array([[-1, -1],
       [-2, -1],
       [ 1,  1],
       [ 2,  1]])

In [77]:
y

array([1, 1, 2, 2])

In [210]:
import numpy as np

from sklearn.pipeline import make_pipeline

from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC

from sklearn.model_selection import cross_val_score
# clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))

# clf.fit(X, y)
# Pipeline(steps=[('standardscaler', StandardScaler()),
#                 ('svc', SVC(gamma='auto'))])



[1.  1.  0.8 1.  1.  1.  1.  1.  1.  1. ]


In [205]:
print(sum(scores)/len(scores))

0.9800000000000001


In [213]:
import random
from sklearn.model_selection import train_test_split

In [235]:
X_train, X_test, y_train, y_test = train_test_split(

    X, y, test_size=0.33, random_state=random.randint(0, 50))



In [236]:
# clf = SVC(kernel='linear', C=1)
# scores = cross_val_score(clf, X_train, y_train, cv=10)
# print(scores)

In [237]:
clf1 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

clf1.fit(X_train, y_train)

predict_y = clf1.predict(X_test)
predict_y

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0])

In [238]:
y_test

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0])

In [240]:
true_pos = 0
true_neg = 0
false_pos = 0
false_neg = 0

i = 0
while (i < len(predict_y)):
    pred = predict_y[i]
    real = y_test[i]
    
    if (pred == real and pred == 1):
        true_pos += 1
    elif (pred == real and pred == 0):
        true_neg += 1
    elif (pred != real and real == 0):
        false_pos += 1
    else:
        false_neg += 1
    
    i += 1
    
    
precision = (true_pos)/(true_pos+false_pos)
recall = (true_pos)/(true_pos+false_neg)
accuracy = (true_pos+true_neg)/(true_pos+true_neg+false_pos+false_neg)
fscore = 2*(precision*recall)/(precision+recall)

In [241]:
precision

1.0

In [242]:
recall

0.75

In [243]:
accuracy

0.8888888888888888

In [244]:
fscore

0.8571428571428571

In [219]:
X_train

array([[4.06799316e-02, 3.21960449e-02, 3.17687988e-02, ...,
        1.70844284e+02, 1.70845520e+02, 1.70815338e+02],
       [7.75451660e-02, 6.88018799e-02, 8.31909180e-02, ...,
        1.37641327e+02, 1.37967133e+02, 1.37851166e+02],
       [6.76269531e-02, 6.47735596e-02, 5.75714111e-02, ...,
        1.70286636e+02, 1.70226517e+02, 1.70493576e+02],
       ...,
       [2.60787964e-01, 2.74902344e-01, 2.62817383e-01, ...,
        1.48763321e+02, 1.48605865e+02, 1.48714477e+02],
       [9.99450684e-02, 8.80737305e-02, 8.09478760e-02, ...,
        1.55921646e+02, 1.55949783e+02, 1.55988098e+02],
       [3.97949219e-02, 3.70941162e-02, 4.84008789e-02, ...,
        1.73296295e+02, 1.73401077e+02, 1.73307434e+02]])

In [220]:
X_test

array([[5.55572510e-02, 5.22308350e-02, 5.53588867e-02, ...,
        1.35620499e+02, 1.35659607e+02, 1.35618240e+02],
       [1.34033203e-01, 1.44424439e-01, 1.52114868e-01, ...,
        1.57091492e+02, 1.57118149e+02, 1.57195450e+02],
       [7.42797852e-02, 6.81762695e-02, 7.02362060e-02, ...,
        1.72530151e+02, 1.72481903e+02, 1.72659103e+02],
       ...,
       [1.11236572e-01, 1.06002808e-01, 1.08520508e-01, ...,
        1.71730041e+02, 1.71601715e+02, 1.71652069e+02],
       [1.26770019e-01, 1.36047363e-01, 1.38229370e-01, ...,
        1.69826721e+02, 1.69740341e+02, 1.69701981e+02],
       [1.24404907e-01, 1.25778198e-01, 1.31240845e-01, ...,
        1.55927689e+02, 1.55942139e+02, 1.55805359e+02]])